stages:
  - build
  - publish

build_project:
  stage: build
  only:
    - dev
    - web
  script:
    - xcodebuild clean -project OrangeTrainingBox.xcodeproj -scheme Baah_FR | xcpretty
    - pod install
    - xcodebuild -allowProvisioningUpdates -scheme Baah_FR -workspace OrangeTrainingBox.xcworkspace  | xcpretty
  tags:
    - ios
    - m1


variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - cd project
  - gem install bundler
  - bundle install

test_flight:
  dependencies: []
  stage: publish
  artifacts:
    paths:
      - ./*.ipa
    expire_in: 1 week
  script:
    - bundle exec fastlane buildAndPublishToTestFlight
  tags:
    - ios
    - m1
  only:
    - web
