stages:
  - build
  - publish

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - cd project
  - gem install bundler
  - bundle install

build_project:
  stage: build
  only:
    - dev
    - web
  script:
    - echo "build for TestFlight" #bundle exec fastlane buildForTestFlight
  tags:
    - ios
    - m1
    
test_flight:
  dependencies:
    - build_project
  stage: publish
  artifacts:
    paths:
      - ./*.ipa
    expire_in: 1 week
  script:
    - pwd
    - ls -ltra
    - bundle exec fastlane publishToTestFlight
  tags:
    - ios
    - m1
  only:
    - web
