stages:
  - build
  - test_flight

build_project:
  stage: build
  only:
    - dev
  script:
    - xcodebuild clean -project OrangeTrainingBox.xcodeproj -scheme Baah_FR | xcpretty
    - pod install
    - xcodebuild -scheme Baah_FR -workspace OrangeTrainingBox.xcworkspace  | xcpretty

  tags:
    - ios
    - m1


variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - gem install bundler
  - bundle install

test_flight_build:
  dependencies: []
  stage: test_flight
  artifacts:
    paths:
      - ./*.ipa
    expire_in: 1 week
  script:
    - fastlane beta
  tags:
    - ios
    - m1
  only:
    - web
 # only:
  #   - /^release-.*$/
   #  - master
